### ISSUE TITLE
control the webview window

### ISSUE THREAD

**Issue by JohnRacism** [neroist/webview#3]
hello, i checked out this library and it's very good, the best webview implementation for nim.
but is there a way to control the webview window, like a way to set the position and access win32/gtk api of this window?

in c++ you could access the hwnd of the window (like here: https://github.com/webview/webview/issues/642#issuecomment-1116763000). i couldn't find any way to do this from nim unfortunately.

thanks!

**Comment by neroist** [comment]
Accessing the window handle may be done with either [`getWindow()`](https://neroist.github.io/webview/#getWindow%2CWebview) or [`getNativeHandle()`](https://neroist.github.io/webview/#getNativeHandle%2CWebview%2CWebviewNativeHandleKind).
